package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.follower.Follower;
import com.qualcomm.robotcore.hardware.HardwareMap;

public class Constants {

    // this will be generated by the tuning of mecanumTuner in Tunning when the steps are followed correctly
//    public static MecanumConfig drivetrainConfig = new MecanumConfig(
//            c -> {
//                c.frontLeftName.set("left_front");
//                c.backLeftName.set("left_back");
//                c.frontRightName.set("right_front");
//                c.backRightName.set("right_back");
//
//                c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
//                c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
//                c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
//                c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
//            }
//    );

    // The localizer config will go here


    // The foresight config will go here
    // remember to go back and look at constraints https://pedropathing.com/docs/pathing/reference/endconstraints
    public static Follower create(HardwareMap h) {
        // Creates the path follower
        // NOTE: Make sure the constants names are correct
        return new Follower(
                new PinpointLocalizer(h, localizerConfig),
                new Mecanum(h, drivetrainConfig),
                new Foresight(foresightConfig)
        );
    }
}